services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rutaexpress-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rutaexpress
      RABBITMQ_DEFAULT_PASS: rutaexpress
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  rabbitmq-data:
